stages:
  - build
  - deploy
build:
  # Official docker image.
  image: docker:dind
  stage: build
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  tags:
    - dev2ops
    
trigger_build:
  stage: deploy
  script:
    - "curl -X POST -F token=21146029ee7f2751ebe9a808363f80 -F ref=master https://gitlab.labranet.jamk.fi/api/v4/projects/5629/trigger/pipeline"
  tags:
    - dev2ops