stages:
  - build
  - deploy
build:
  # Official docker image.
  image: docker:stable
  stage: build
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"

  variables:
    # Configure mysql environment variables (https://hub.docker.com/_/mysql/)
    Host: mysql
    User: admin_user
    Password: P#q3dJ/4
    Database: wordpress

  tags:
    - dev2ops
    
trigger_build:
  stage: deploy
  script:
    - "curl -X POST -F token=7387359b4e4df97c697691384782ee -F ref=master https://gitlab.labranet.jamk.fi/api/v4/projects/5629/trigger/pipeline"
  tags:
    - dev2ops