stages:
  - build
  - deploy
build:
  # Official docker image.
  image: docker:dind
  stage: build
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  tags:
    - dev2ops
  
  services:
    - mysql:latest

  variables:
    # Configure mysql environment variables (https://hub.docker.com/_/mysql/)
    MYSQL_DATABASE: "wordpress"
    MYSQL_ROOT_PASSWORD: "wPrP80"
    Host: mysql
    User: root
    Password: P#q3dJ/4
    Database: wordpress
  tags:
    - dev2ops
    
trigger_build:
  stage: deploy
  script:
    - "curl -X POST -F token=TOKEN -F ref=REF_NAME https://gitlab.labranet.jamk.fi/api/v4/projects/5629/trigger/pipeline"
  tags:
    - dev2ops