version: '3.3'

services:
   db:
     container_name: mysql
     image: mysql
     ports:
       - "3306:3306"
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: password
       MYSQL_DATABASE: wordpress
       MYSQL_USER: admin_user
       MYSQL_PASSWORD: P#q3dJ/4

   wordpress:
     container_name: wordpress
     depends_on:
       - db
     image: wordpress
     ports:
       - "8080:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: mysql
       WORDPRESS_DB_USER: admin_user
       WORDPRESS_DB_PASSWORD: P#q3dJ/4
       WORDPRESS_DB_NAME: wordpress
networks:
  default:
    external:
      name: WP_network
volumes:
    db_data: {}
WORDPRESS_DB_NAME: wordpress
networks:
  default:
    external:
      name: WP_network
volumes:
    db_data: {}

